# Generated by Django 3.2.2 on 2021-05-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubHouseRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('cover', models.FileField(upload_to='covers/')),
                ('club_house_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.clubhouseroom')),
            ],
        ),
    ]
