# Generated by Django 3.2.2 on 2021-05-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='club_house_room',
            new_name='room',
        ),
    ]
